name       : hunspell-uk
version    : 4.4.2
release    : 2
source     :
    - https://github.com/brown-uk/dict_uk/archive/v4.4.2.tar.gz : 3041f3f838477b812a8463fe51129d8929b2c6f2c3c428788666c5b8d5c52d30
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : spelling
networking : yes
summary    : Ukrainian hunspell dictionary
description: |
    Ukrainian spelling dictionary for hunspell.
builddeps  :
    - gradle
build      : |
    export GRADLE_USER_HOME=~/
    export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8

    cd distr/hunspell
    gradle --no-daemon hunspell
install    : |
    cd distr/hunspell/build/hunspell
    install -Dm00644 uk_UA.{aff,dic} -t $installdir/usr/share/hunspell
