name       : hunspell-uk
version    : 5.9.0
release    : 5
source     :
    - https://github.com/brown-uk/dict_uk/releases/download/v5.9.0/hunspell-uk_UA_5.9.0.zip : 496d0e1e1f9a3f18616c9c0ebe3541c59828f1335d896e643f966b91ed87f844
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - MPL-1.1
component  : spelling
summary    : Ukrainian hunspell dictionary
description: |
    Ukrainian spelling dictionary for hunspell.
install    : |
    install -Dm00644 uk_UA.{aff,dic} -t $installdir/usr/share/hunspell
